### ISSUE TITLE
Add Unit Tests 

### ISSUE THREAD

**Issue by developerfred** [viant/bqtail#2]
The higher the test coverage, the better your project will be ranked.

Check this
[Run Go Unit Tests mode easy] (https://medium.com/rungo/unit-testing-made-easy-in-go-25077669318)
[Learning Go with Tests](https://github.com/quii/learn-go-with-tests)

**Comment by adranwit** [comment]
Thanks for the feedback.
It makes all sense, I do add unit test when it makes sense, using data-driven approach, but since this project entirely uses serverless, and GCP with BigQuery API/Slack/Storage API, I've put all effort to e2e testing. All that said there is always room for improving unit tests.

**Comment by developerfred** [comment]
Yes, that's why I closed the issue, when I analyzed the project better. Glad you read it. 👍
